name: Flutter Linux Build

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang cmake ninja-build pkg-config \
            libgtk-3-dev liblzma-dev

      - name: Set up latest Flutter stable
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop

      - name: Install Dart & Flutter packages
        run: flutter pub get

      - name: Upgrade win32 & archive to Dart 3.5 compatible versions
        run: flutter pub upgrade win32 archive

      - name: Build Linux release
        run: flutter build linux --release

      - name: Upload Linux build artifact
        uses: actions/upload-artifact@v4
        with:
          name: coom-dl-linux
          path: build/linux/x64/release/bundle
